const AUDIT_ACTIONS = Object.freeze({
  // Users (étape 3)
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ARCHIVED: 'USER_ARCHIVED',

  // Galeries
  GALLERY_CREATED: 'GALLERY_CREATED',
  GALLERY_UPDATED: 'GALLERY_UPDATED',
  GALLERY_ARCHIVED: 'GALLERY_ARCHIVED',

  // Boutiques
  SHOP_CREATED: 'SHOP_CREATED',
  SHOP_UPDATED: 'SHOP_UPDATED',
  SHOP_ARCHIVED: 'SHOP_ARCHIVED',

  // Compteurs
  METER_CREATED: 'METER_CREATED',
  METER_UPDATED: 'METER_UPDATED',
  METER_ARCHIVED: 'METER_ARCHIVED',

  // Relevés
  READING_CREATED: 'READING_CREATED',
  READING_INVALIDATED: 'READING_INVALIDATED',
  READING_CORRECTED: 'READING_CORRECTED',

  // Placeholders étapes 5-6
  PURCHASE_CREATED: 'PURCHASE_CREATED',
  PURCHASE_CANCELLED: 'PURCHASE_CANCELLED',
  BALANCE_RECALCULATED: 'BALANCE_RECALCULATED',
  POWER_EVENT_CREATED: 'POWER_EVENT_CREATED',
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  INCIDENT_STATUS_UPDATED: 'INCIDENT_STATUS_UPDATED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',
});

module.exports = { AUDIT_ACTIONS };