const DEFAULT_LOW_THRESHOLD_KWH = 50;
const DEFAULT_CRITICAL_THRESHOLD_KWH = 10;
const DEFAULT_AVERAGE_PERIOD_DAYS = 7;

module.exports = {
  DEFAULT_LOW_THRESHOLD_KWH,
  DEFAULT_CRITICAL_THRESHOLD_KWH,
  DEFAULT_AVERAGE_PERIOD_DAYS,
};