const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  GALLERY_ADMIN: 'GALLERY_ADMIN',
  TECHNICIAN: 'TECHNICIAN',
  SHOP_OWNER: 'SHOP_OWNER',
  SHOP_WORKER: 'SHOP_WORKER',
});

const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  ARCHIVED: 'ARCHIVED',
});

module.exports = { ROLES, USER_STATUS };